### ISSUE TITLE
Alias issue Please help

### ISSUE THREAD

**Issue by Dezzrevas** [nextcloud/integration_zimbra#25]
There was an email that was removed from the hosting, the address was moved to be an alias to someone on the same domain. Somehow this email alias ended up on another email in the list. 

The alias was added to the correct account but after saving it showed up on the completely different email. The email in the list was from a different domain that had an alias to the domain where the target email resides. The target email did not have the alias after this. 

Can anyone think of a reason this would happen? 

The servers where the email data is stored is in between a change from Midlands to AWS data centers. Also the logs don't show the correct action being made. However the correct actions were made with no error.

**Comment by provokateurin** [comment]
This does not sound related to this Nextcloud integration.
